print('Olá, por favor, preencha os campos abaixo de acordo com sua data de nascimento:')
dia = input('Dia:')
mês = input('Mês:')
ano = input('Ano:')
print('Você nasceu no dia', dia, 'de', mês, 'de', ano, '. Correto?')